version = 5.6.0
archive_dir = /etc/letsencrypt/archive/payload.presspizza.com
cert = /etc/letsencrypt/live/payload.presspizza.com/cert.pem
privkey = /etc/letsencrypt/live/payload.presspizza.com/privkey.pem
chain = /etc/letsencrypt/live/payload.presspizza.com/chain.pem
fullchain = /etc/letsencrypt/live/payload.presspizza.com/fullchain.pem
[renewalparams]
account = 27b6db52b2f1bcf518f40df8525d642d
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-06-27T04:52:36
